// The Kimi provider - Moonshot AI's `kimi` CLI.
//
// Ported from jupyterlab_kimi_code_extension v0.7.8. Everything that made that
// extension different from the base one is declared here as descriptor data,
// so no core file knows this assistant exists:
//
// * `forkStrategy: 'server-copy'` - kimi has no fork verb at all, so the
//   server copies the session directory and answers with the new id
// * `colourSource: 'derived'` - kimi has no `/color`, so the default tint is a
//   stable hash of the conversation id (a user-set colour still wins, per the
//   Colour section of the acceptance criteria)
// * `namingStrategy: 'server-side'` - the name is stamped into the copied
//   `state.json`, not passed to the CLI
// * one launch mode, `--yolo`, under kimi's own name
//
// The only hook is the branch label: kimi's conversation titles are
// auto-generated by a Chinese-first model, and both the session id shape and
// the glyph widths of those titles need handling the shared default cannot do.

import { IBranch, IProviderDescriptor, IProviderHooks } from '../core/types';

// Crescent moon (Kimi is Moonshot AI's CLI) - an outer semicircle on the left,
// bitten from the right by a wider inner arc.
const kimiSvgStr = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
  <g class="jp-icon3" fill="#616161">
    <path d="M8 1.5A6.5 6.5 0 1 0 8 14.5 8 8 0 0 1 8 1.5Z"/>
  </g>
</svg>`;

// ------------------------------------------------------------------- labels

// Budget is in COLUMNS, not characters. Han, Kana, Hangul and emoji render at
// roughly one em against Latin's half, so counting characters bounds nothing:
// 60 Han glyphs measured 851-862px in a real Lumino submenu, at or above the
// 850px that filed the defect in the first place. Kimi is Moonshot AI's CLI,
// so a Chinese auto-generated title is the expected case, not an exotic one.
export const MENU_TITLE_COLUMNS = 60;

// East Asian Wide and Fullwidth ranges, plus emoji. Deliberately coarse: this
// bounds a menu width, so a handful of mis-classified glyphs cost pixels, not
// correctness. Anything outside these ranges counts as one column.
const WIDE_RANGES: ReadonlyArray<readonly [number, number]> = [
  [0x1100, 0x115f], // Hangul Jamo
  [0x2e80, 0x303e], // CJK radicals, Kangxi, CJK symbols and punctuation
  [0x3041, 0x33ff], // Hiragana, Katakana, Bopomofo, Hangul Compat, CJK Compat
  [0x3400, 0x4dbf], // CJK Unified Extension A
  [0x4e00, 0x9fff], // CJK Unified Ideographs
  [0xa000, 0xa4cf], // Yi
  [0xac00, 0xd7a3], // Hangul syllables
  [0xf900, 0xfaff], // CJK Compatibility Ideographs
  [0xfe30, 0xfe6f], // CJK Compatibility Forms
  [0xff00, 0xff60], // Fullwidth forms
  [0xffe0, 0xffe6], // Fullwidth signs
  [0x1f300, 0x1faff], // Emoji and pictographs
  [0x20000, 0x3fffd] // CJK Unified Extensions B and beyond
];

function isWide(codePoint: number): boolean {
  return WIDE_RANGES.some(([lo, hi]) => codePoint >= lo && codePoint <= hi);
}

/** Trim `text` to `maxColumns` display columns, appending an ellipsis when
 * anything was cut. Iterates by CODE POINT, so an astral character is never
 * split into a lone surrogate (which chromium paints as the replacement
 * glyph). Returns `text` unchanged when it already fits. */
export function truncateToColumns(text: string, maxColumns: number): string {
  let columns = 0;
  let kept = '';
  for (const ch of text) {
    const width = isWide(ch.codePointAt(0) as number) ? 2 : 1;
    if (columns + width > maxColumns) {
      // The cut can land just after a space; drop it so the ellipsis hugs the
      // last word. `trimEnd` is ES2019 and this project targets ES2018.
      return `${kept.replace(/\s+$/, '')}…`;
    }
    columns += width;
    kept += ch;
  }
  return text;
}

/** The distinguishing part of a kimi session id.
 *
 * Kimi ids are `session_<uuid>`, so the core's front-slice would render the
 * constant `session_` for every conversation of a project - the exact thing
 * the short id exists to tell apart. Slice past the prefix instead.
 */
export function shortSessionId(sessionId: string): string {
  return sessionId.startsWith('session_')
    ? sessionId.slice(8, 16)
    : sessionId.slice(0, 8);
}

/** Menu-item label for one branch: the conversation title trimmed to the
 * column budget, followed by the short session id. Only the TITLE is trimmed -
 * branches of one project share a path, so the id is what tells them apart and
 * it must survive. The bracketed id is dropped when the title already IS the
 * id (the server's last-resort fallback), which can never be truncated since a
 * short id is at most 8 characters. */
export function branchMenuLabel(label: string, shortId: string): string {
  const title = truncateToColumns(label, MENU_TITLE_COLUMNS);
  return label === shortId ? title : `${title} (${shortId})`;
}

// -------------------------------------------------------------- descriptor

export const descriptor: IProviderDescriptor = {
  id: 'kimi',
  label: 'Kimi',
  panelTitle: 'Kimi Code Sessions',
  iconName: 'jupyterlab_ai_code_assistants_extension:kimi',
  iconSvg: kimiSvgStr,
  cliBinary: 'kimi',
  // No fork flag exists, so the server copies the session directory under a
  // fresh id and the launch resumes that id like any other conversation.
  forkStrategy: 'server-copy',
  // No `/color` command either: the tint is derived from the conversation id.
  // The core's own FNV-1a is the same hash over the same six ids the retired
  // extension used, so every conversation keeps the colour it already had.
  colourSource: 'derived',
  // The fork's name is written into the copy's `state.json` by the server; the
  // CLI has no naming flag to take it.
  namingStrategy: 'server-side',
  // A bare `kimi` mints its own id and writes it on the first turn, and `-S`
  // only ever resumes - so a new conversation cannot be launched under an id
  // we chose, and is identified from the store on the next poll instead.
  mintsNewSessionId: false,
  launchModes: [
    {
      id: 'yoloMode',
      title: 'YOLO mode',
      description:
        'When enabled, newly spawned and resumed sessions are launched with `--yolo`. Kimi auto-approves regular tool calls without asking - only enable in workspaces you trust.',
      kind: 'boolean',
      default: false,
      menuLabel: 'YOLO'
    }
  ],
  hasRemoteControl: false,
  hasBgAgents: false,
  hasLiveProcess: false,
  // Retired standalone extension this provider replaces.
  legacyPluginId: 'jupyterlab_kimi_code_extension'
};

// ------------------------------------------------------------------- hooks

export const hooks: IProviderHooks = {
  /** Lumino sets no `max-width` on `.lm-Menu-itemLabel`, so an uncapped
   * auto-generated title stretches the submenu across the window. The core's
   * `shortId` argument is a front-slice, which is the constant `session_` for
   * every kimi id, so the id is re-derived here. */
  branchLabel: (branch: IBranch, _shortId: string): string =>
    branchMenuLabel(branch.label, shortSessionId(branch.session_id))
};
